name: agrost
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #inner packages
  domain:
    path: ./packages/domain

  #Firebase scope
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  firebase_ui_firestore: ^1.3.2

  #design packages
  google_fonts: ^4.0.3
  flex_color_scheme: ^7.0.3
  antd_mobile: ^0.1.0

  #Other scope
  get: 4.6.5
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  transparent_image: ^2.0.1
  reactive_forms: ^14.3.0
  intl: ^0.18.1
  either_dart: ^0.3.0

dependency_overrides:
  intl: ^0.18.1


dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.2
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter:
  fonts:
    - family: PlantIcons
      fonts:
        - asset: fonts/PlantIcons.ttf
    - family: Futura
      fonts:
        - asset: fonts/Futura-Bold.ttf
        - asset: fonts/Futura-Medium.ttf
  uses-material-design: true

