name: agrost
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #inner packages
  domain:
    path: ./packages/domain

  #Firebase scope
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  firebase_ui_firestore: 1.4.0

  #design packages
  google_fonts: ^4.0.4
  flex_color_scheme: ^7.0.4
  antd_mobile: ^0.1.0
  plant_icons:
    path: ../plant_icons

  #Work with device memory
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15

  #Other scope
  get: 4.6.5
  json_serializable: ^6.6.1
  json_annotation: ^4.8.1
  transparent_image: ^2.0.1
  reactive_forms: ^15.0.0
  intl: ^0.18.1
  either_dart: ^0.4.0
  firebase_storage: ^11.2.1

dependency_overrides:
  intl: ^0.18.1


dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.4
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/custom_images/
    - assets/essentials/

  fonts:
    - family: Futura
      fonts:
        - asset: fonts/Futura-Bold.ttf
        - asset: fonts/Futura-Medium.ttf
  uses-material-design: true

