name: agrost
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #inner packages
  domain:
    path: ./packages/domain

  #Firebase scope
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  firebase_ui_firestore: ^1.2.10

  #Other scope
  get: 4.6.5
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  cached_network_image: ^3.2.3
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

